name: tripoli_shop
description: "Tripoli Shop App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  http: ^1.6.0
  get_storage: ^2.1.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  maps_toolkit: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#0B3D2E"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png